// pages/app/conversation/[id].tsx
import Input from "@/components/ui/Input";
import Textarea from "@/components/ui/Textarea";
import { getToken } from "@/lib/auth";
import { getConversationName } from "@/lib/conversation";
import { prettyDate } from "@/lib/date";
import { useAuth } from "@/store/auth";
import { ApiResponse } from "@/types/api";
import { Conversation, Message } from "@/types/types";
import { BarChart, BarrelIcon, Fingerprint, Lock, Menu, Send, ShoppingCart, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { KeyboardEventHandler, ReactNode, useEffect, useLayoutEffect, useRef, useState } from "react";
import { getSocket } from "@/socket";
import { useAutoAnimate } from '@formkit/auto-animate/react';
import autoAnimate from "@formkit/auto-animate";
import { decryptWithAES, decryptWithRSA, encryptWithAES, generateConversationFingerprint, getConversationAES, getConversationMembersPublicKey } from "@/lib/key";
import Hr from "@/components/general/Hr";

export default function ConversationId() {
    const socket = getSocket();
    const auth = useAuth();
    const router = useRouter();

    let { id } = router.query;

    const messagesDiv = useRef<HTMLDivElement>(null);

    const [conversation,setConversation] = useState<Conversation|null>(null);
    const [messages,setMessages] = useState<Message[]>([]);

    const [message,setMessage] = useState<string>("");

    const [aesKey,setAesKey] = useState<CryptoKey|null>(null);
    const [fingerPrint,setFingerPrint] = useState<string>("");

    const scrollTopMessages = () => {
        setTimeout(() => {
            if(!messagesDiv.current) return;

            messagesDiv?.current.scrollTo({
                top:messagesDiv.current?.scrollHeight
            });
        }, 1);
    };

    useEffect(() => {
        if(!id) return;
        id = id.toString();

        (async() => {
            const token = getToken();
    
            let res = await fetch(`/api/conversation/${id}/messages`,{
                headers:{
                    Authorization:token,
                }
            });
    
            let json:ApiResponse<Message[]> = await res.json();
    
            if(!json.data) return router.push("/app");
    
            const privateKey = localStorage.getItem("privateKey");
            if (!privateKey) return;

            const AES = await getConversationAES(id,privateKey,auth.user?.id);
            if(!AES) return;

            setAesKey(AES);

            json.data.forEach(async(msg) => {
                try {
                    msg.content = await decryptWithAES(msg.content,msg.iv,AES);
                } catch (error) {
                    console.log(error);
                }
            });

            setMessages(json.data.reverse());

            const waitForMessagesDiv = () => {
                if(!messagesDiv.current) return requestAnimationFrame(waitForMessagesDiv);
                scrollTopMessages();
            };

            waitForMessagesDiv();

            let publicKeys = await getConversationMembersPublicKey(id);
            let fingerPrint = await generateConversationFingerprint(publicKeys);
            console.log(`Conversation Fingerprint: ${fingerPrint}`);
            setFingerPrint(fingerPrint);
        })();

        (async() => {
            const token = getToken();
    
            let res = await fetch(`/api/conversation/${id}`,{
                headers:{
                    Authorization:token,
                }
            });
    
            let json:ApiResponse<Conversation> = await res.json();
    
            if(!json.data) return;

            setConversation(json.data);

            setTimeout(() => {
                messagesDiv.current && autoAnimate(messagesDiv.current);
            }, 100);
        })();

        const onMessage = async(data:{conversation:Conversation,data:Message}) => {
            if(data.conversation.id != id) return;

            setAesKey((aes) => {
                if(!aes) return aes;

                (async() => {
                    const content = await decryptWithAES(data.data.content,data.data.iv,aes);

                    data.data.content = content;

                    setMessages((prevMessages) => [...prevMessages,data.data]);
                    if(Math.abs(messagesDiv.current?.scrollHeight-messagesDiv.current?.clientHeight-messagesDiv.current?.scrollTop) < 10){
                        setTimeout(() => {
                            scrollTopMessages();
                        }, 0);
                    };
                })();

                return aes;
            });

            /*let audio = document.createElement("audio");
            audio.src = "/notification.mp3";
            audio.play();*/
        };

        socket?.on("message",onMessage);

        return () => {
            socket?.off("message",onMessage);
        };
    },[]);

    const createMessage = async() => {
        if(!message) return;

        try {
            if(!aesKey) return;

            let {content,iv} = await encryptWithAES(message,aesKey);

            const token = getToken();
    
            let res = await fetch(`/api/conversation/${id}/messages/create`,{
                headers:{
                    Authorization:token,
                    "Content-Type":"application/json"
                },
                body:JSON.stringify({
                    content,
                    iv
                }),
                method:"POST",
            });
    
            let json:ApiResponse<Message> = await res.json();
    
            if(!json.data || !json.success) return;
                        
            //setMessages([...messages,json.data]);

            setMessage("");

            if(Math.abs(messagesDiv.current?.scrollHeight-messagesDiv.current?.clientHeight-messagesDiv.current?.scrollTop) < 10){
                setTimeout(() => {
                    scrollTopMessages();
                }, 0);
            };
        } catch (error) {
            console.log(error);
        }
    };

    const keydown:KeyboardEventHandler<HTMLTextAreaElement> = (ev) => {
        if(ev.key == "Enter" && !ev.ctrlKey){
            ev.preventDefault();
            createMessage();
        };

        if(ev.key == "Enter" && ev.ctrlKey){
            ev.preventDefault();
            const textarea = ev.currentTarget;

            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            
            const newText = message.substring(0, start) + '\n' + message.substring(end);
            setMessage(newText);
            
            setTimeout(() => {
                textarea.selectionStart = textarea.selectionEnd = start + 1;
            }, 0);
        };
    };

    useEffect(() => {
        messagesDiv.current && autoAnimate(messagesDiv.current);
    },[messagesDiv]);

    const [conversationMenu,setConversationMenu] = useState<boolean>(false);

    if(!conversation) return (<></>);

    return (
        <div className="w-full flex flex-col items-start gap-3 h-screen p-4">
            <div onClick={() => setConversationMenu(!conversationMenu)} className="cursor-pointer w-full py-2 px-4 bg-gray-800/70 border-2 border-gray-700 backdrop-blur-sm rounded-full flex flex-row items-center justify-between gap-3 shadow">
                <div className="flex flex-row items-center gap-3">
                    <img src="/anomz.png" width={32} draggable={false} alt="" />
                    <span className="font-semibold">{getConversationName(auth.user,conversation)}</span>
                </div>
                <div>
                    <Menu className="cursor-pointer" size={32}/>
                </div>
            </div>
            <div className="flex-1 flex flex-col w-full bg-gray-700 rounded-lg mb-3 py-4 px-4 gap-5 relative overflow-clip">
                <div className={`rounded-r-lg p-4 absolute z-30 bg-gray-800 top-0 w-1/2 h-full duration-300 gap-3 ${conversationMenu ? 'visible opacity-100 right-0' : 'invisible opacity-0 -right-[100vh]'} flex flex-col items-start`}>
                    <div className="w-full flex flex-col items-center gap-3">
                        <img className="select-none" src="/anomz.png" draggable={false} width={64} alt="" />
                        <span className="text-lg font-semibold">{conversation.name}</span>
                    </div>
                    <span className="text-xs font-bold select-none text-gray-400">MEMBERS ({conversation.participants?.length})</span>
                    <div className="flex flex-col items-start gap-3 select-none font-semibold">
                        {conversation.participants?.map((par) => (
                            <div className="flex flex-row items-center gap-3">
                                <img src="/anomz.png" draggable={false} width={32} alt="" />
                                <span>{par.user?.username} - {par.role}</span>
                            </div>
                        ))}
                    </div>
                    <Hr/>
                    <span className="font-semibold">Created At: {new Date(conversation.createdAt).toLocaleDateString("en-GB",{hour:"numeric",minute:"numeric",second:"numeric"})}</span>
                    <Hr/>
                    <span>Conversation Fingerprint: <strong>{fingerPrint}</strong></span>
                    <div className="flex flex-row items-center gap-3 font-semibold">
                        <Lock className="text-green-400" size={20}/>
                        <span>End-To-End Encryption</span>
                    </div>
                    <Hr/>
                </div>
                <div ref={messagesDiv} className="flex flex-col overflow-y-scroll flex-1 gap-3" style={{
                    flexBasis:"0px"
                }}>
                    {messages.map((_, i) => (
                        <div key={_.id} className={`w-full flex flex-col ${_.sender?.id == auth.user?.id ? 'items-end' : 'items-start'}`}>
                            <div className={`${_.sender?.id == auth.user?.id ? 'bg-blue-600' : 'bg-gray-600'} py-2 px-4 rounded flex flex-col items-start`}>
                                <div className="flex flex-row items-center gap-3 mb-2">
                                    <img className="select-none" src="/anomz.png" width={32} draggable={false} alt="" />
                                    <span>{_.sender?.username || "System"}</span>
                                </div>
                                <span style={{whiteSpace:"pre-wrap"}}>{_.content}</span>
                                <span className="text-xs text-blue-300">{prettyDate(new Date(_.createdAt))}</span>
                            </div>
                        </div>
                    ))}
                </div>
                <div className="shadow-xl w-full bg-gray-600 rounded flex flex-row items-center gap-3 pr-6 py-2 px-4">
                    <Textarea onKeyDown={keydown} value={message} onChange={(e) => setMessage(e.target.value)} rows={1} className="w-full h-full border-0! rounded bg-transparent" placeholder="Message..."/>
                    <button onClick={createMessage}>
                        <Send className="cursor-pointer" size={24}/>
                    </button>
                </div>
                {/*<div className="w-full flex lg:flex-row flex-col lg:items-center items-start gap-3 justify-between">
                    <span>Conversation Fingerprint: <strong>{fingerPrint}</strong></span>
                    <span>{new Date(Date.now()).toLocaleDateString("tr",{
                        hour:"numeric",
                        minute:"numeric",
                        second:"numeric"
                    })}</span>
                </div>*/}
            </div>
        </div>
    );
}

// pages/dashboard/groups/[id].vue
<script setup>

    definePageMeta({
        middleware: [
            'auth',
        ],
    });

    const {public:{apiUrl}} = useRuntimeConfig();
    const token = useCookie("token");

    const myUser = useState("user");

    const group = ref(null);
    const messages = ref([]);

    const loading = ref(true);

    const route = useRoute();
    const id = ref(route?.params?.id);

    const message = ref("");

    const main = ref("");

    const modalActive = ref(false);
    const sock = useState("sock");

    (async() => {
        let res = await useFetch(`${apiUrl}/api/group/${id.value}`,{
            headers:{
                authorization:token.value
            }
        });

        group.value = res.data.value.find;
        
        loading.value = false;
    })();

    (async() => {
        let res = await useFetch(`${apiUrl}/api/group/${id.value}/messages`,{
            headers:{
                authorization:token.value
            }
        });

        messages.value = res.data.value.find.slice().reverse();;
        
        if(!process.client) return;

        nextTick(() => {
            main.value.scrollTo({
                top: main.value.scrollHeight,
                left: 0,
                behavior:"instant"
            });
        });
    })();

    const sendMessage = async() => {
        if(!message.value) return;
        
        let fakeId = Math.random()*Date.now();

        messages.value.push({
            content:message.value,
            from:myUser.value,
            loading:true,
            fakeId
        });

        nextTick(() => {
            main.value.scrollTo({
                top: main.value.scrollHeight,
                left: 0,
                behavior:"instant"
            });
        });

        fetch(`${apiUrl}/api/group/${id.value}/messages/create`,{
            method:"POST",
            body:JSON.stringify({
                content:message.value
            }),
            headers:{
                Authorization:token.value,
                'Content-Type':'application/json'
            }
        }).then(() => {
            messages.value.find((e) => e?.fakeId == fakeId).loading = false;
        });

        message.value = "";
    };

    const loadingNewMessages = ref(false);
    const loadedMaxMessages = ref(false);

    const scroll = async() => {
        if(main.value.scrollTop > 100 || loadedMaxMessages.value || loadingNewMessages.value) return;
        
        loadingNewMessages.value = true;

        let initialHeight = main.value.scrollHeight;

        let res = await fetch(`${apiUrl}/api/group/${group.value.id}/messages?cursor=${messages.value[0].id}`,{
            headers:{
                Authorization:token.value
            }
        });
        let json = await res.json();

        if(json.find.length < 1) {
            loadingNewMessages.value = false;
            return loadedMaxMessages.value = true;
        }

        messages.value = [...json.find.slice().reverse(),...messages.value];

        nextTick(() => {
            main.value.scrollTo({
                top: main.value.scrollHeight-initialHeight,
                left: 0,
                behavior:"instant"
            });

            loadingNewMessages.value = false;
        });
    };

    onMounted(() => {
        nextTick(() => {
            sock.value.removeAllListeners("message");

            sock.value.on('message',(t) => {
                if(t.group && t.group == group.value.id){
                    messages.value.push(t.message);
                    nextTick(() => {
                        main.value.scrollTo({
                            top: main.value.scrollHeight,
                            left: 0,
                            behavior:"instant"
                        });
                    });
                };
            });
        }); 
    });
</script>

<template>
    <div class="w-full h-full flex flex-row items-center lg:justify-normal justify-center">
        <dashnav/>
        <div :class="`lg:w-5/6 w-full h-full flex flex-col items-center p-4`">
            <div v-if="group" :class="`w-full h-full fixed top-0 left-0 bg-black/30 z-50 flex items-center justify-center duration-300 ${modalActive ? 'opacity-100 visible' : 'opacity-0 invisible'}`">
                <div :class="`lg:w-2/3 lg:h-2/3 w-full h-full bg-gray-800 rounded-lg flex flex-col border-2 border-gray-700 duration-300 ${modalActive ? 'scale-100' : 'scale-0'}`">
                    <div class="flex flex-row items-center justify-between w-full p-4 border-b-2 border-gray-700">
                        <div class="flex flex-row items-center gap-3">
                            <img :src="group.profilePhoto" draggable="false" width="32" alt="">
                            <span>{{ group.name }}</span>
                        </div>
                        <button @click="modalActive = false;">X</button>
                    </div>
                    <div class="flex flex-col gap-3 overflow-auto p-4">
                        <span>Kullanıcılar</span>
                        <button v-for="user in group.users" :key="user.id" class="w-full gap-3 bg-gray-700 rounded-full flex flex-row items-center justify-between py-2 px-4">
                            <div class="flex flex-row items-center gap-3">
                                <img draggable="false" :src="user.profilePhoto" class="rounded-full" width="32" alt="">
                                <span>{{ user.username }}</span>
                            </div>
                            <i v-if="group.ownerId == user.id" class="fa-solid fa-chess-king text-yellow-600"></i>
                        </button>
                        <span></span>
                        <button class="w-full bg-gray-700 rounded-full flex flex-row items-center justify-between py-2 px-4">
                            <span>Add user</span>
                            <i class="fa-solid fa-user-plus"></i>
                        </button>
                    </div>
                </div>
            </div>
            <button v-if="group" @click="modalActive = true;" class="flex flex-row items-center bg-gray-800 py-2 px-4 rounded-full w-full gap-3">
                <img width="32" height="32" draggable="false" class="rounded-full" :src="group.profilePhoto" alt="">
                <span>{{ group.name }}</span>
            </button>
            <div v-if="messages.length > 0" @scroll="scroll" ref="main" class="w-full h-full flex flex-col overflow-y-scroll">
                <div v-if="loadingNewMessages" class="w-full flex items-center justify-center">
                    <Loading/>
                </div>
                <div v-for="msg in messages" :key="msg.id" class="flex flex-col w-full hover:bg-gray-700 py-2 px-4 relative">
                    <div v-if="msg.loading" class="absolute w-full h-full bg-black/30 top-0 left-0 flex items-center justify-center">
                        <Loading/>
                    </div>
                    <div class="flex flex-row w-full justify-between items-center relative">
                        <div class="flex flex-col items-start gap-2 w-full">
                            <div v-if="msg.from && !msg.system" class="flex flex-row items-center gap-2 cursor-pointer">
                                <img class="w-[32px] h-[32px] rounded-full" alt="" draggable="false" :src="msg.from.profilePhoto" width="32">
                                <span>{{ msg.from.username }}</span>
                            </div>
                            <div v-else class="flex flex-row items-center gap-2 cursor-pointer">
                                <img class="w-[32px] h-[32px] rounded-full" alt="" draggable="false" src="/anomz2.png" width="32">
                                <span>System</span>
                            </div>
                            <span class="select-text whitespace-normal w-full max-w-full">{{ msg.content }}</span>
                        </div>
                        <div class="absolute right-0 flex flex-row items-center gap-2">
                            <!--<i :id="`msg_delete_btn_${msg?.id}`" v-if="msg?.from?.id == myUser.id" @click="deleteMessage(msg?.id)" class="fa-solid fa-trash hover:text-red-600 cursor-pointer duration-300 shake flex"></i>
                            <i @click="copyClipBoard(msg.content)" class="fa-solid fa-copy hover:text-blue-600 cursor-pointer duration-300"></i>-->
                        </div>
                    </div>
                </div>
            </div>
            <form @submit.prevent="sendMessage" class="w-full flex flex-row items-center rounded-full px-4 bg-gray-800">
                <input v-model="message" class="rounded-full w-full bg-transparent" placeholder="message" type="text">
                <button><i class="fa-solid fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</template>
